server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: web_chat
  username: root
  password: yourMysqlPsw
  charset: utf8mb4
oss:
  OSSBucket: yourBucket
  OSSEndpoint: yourEndpoint
  OSSAccessKeyID: yourAccessKeyID
  OSSAccessKeySecret: yourAccessKeySecret